### ISSUE TITLE
Can't disable fb-inset with fancy-buttons 1.0.4

### ISSUE THREAD

**Issue by johnthedebs** [imathis/fancy-buttons#17]
I've updated to fancy-buttons 1.0.4 (the latest I get through `gem update`) and it no longer respects setting `$fb-inset: false`. Took a look at the code on my system (as the 1.0.4 commits aren't on github), and it seems like the check for it was removed between 1.0.3 and 1.0.4.

**Comment by imathis** [comment]
Thanks for the report. I believe I removed that because I felt that the buttons looked nicer and the setting was fairly useless. I reasoned that no one would probably turn it off and so I removed it.

I'm not against adding it back, but I just thought it was unnecessary. Since you find it useful, I'd like to know why. Do you dislike the look of the inset highlight? Could it be improved to be more suitable for you? Or do you have some other reason for disabling it?

**Comment by johnthedebs** [comment]
I think it improves the look of the button in most cases, but I prefer the old look for smaller buttons where the inset can be overwhelming and (especially) buttons on dark backgrounds.

**Comment by imathis** [comment]
Ok, that's what I wanted to hear, thanks. I'll add it back in after I return from holiday traveling. Can you use 1.0.3 for now or does that cause problems?

I'm planning to introduce multiple themes at some point soon to give more variety and make it so users don't have to fool around with setting global variables to get the style they like. When Compass 0.11 and Sass 3.1 are released, I'll get cracking on that.

**Comment by johnthedebs** [comment]
I'm not in a rush, but thanks for the quick response!

Multiple themes sounds like a good idea, I'll be looking forward to that.
