### ISSUE TITLE
default font

### ISSUE THREAD

**Issue by rvr** [imathis/fancy-buttons#22]
i'd prefer it if the plugin didn't set a font-family. this should be at least available to override with a config variable. there are other areas where i would prefer it be more design-agnostic, too, such as text-shadow style.

**Comment by imathis** [comment]
You can override the font-family quite easily:
button { @include fancy-buttons; font-family: "Helvetica Neue" sans; }

If I didn't set the font-family, it would by default inherit a font. In many cases that's not desirable. If you want a specific font, you can set one like I did above. If not, you don't have to worry about inheritance. Text shadow is a bit more tricky because the color of the text shadow is determined by the color passed in to fancy-buttons. If you want to turn text-shadows off, you can set text-shadow: none !important; and that should work. If you're looking for a different kind of text shadow, you can use that too, but you'll probably have to add :active and :hover,:focus states for the text shadow as well.

Right now fancy-buttons is easy to use if you don't need a lot of customization, but it's not very easy if you're going for something specific. In 2.0 I hope to change that.

In fancy-buttons 2.0 I'll be shipping several different themes. At that point I'll be dropping most of the default variables. Then you could use one of the many themes that come with it, extend a theme and change things to be how they want them, or write your own theme from scratch. Compass 0.11 comes with lots of new toys that make this possible, so I'm still figuring it out.

**Comment by rvr** [comment]
well yes, that is obviously the way to override the default font :) i did that. the thing is, i have to override it each time i apply it if i use it on specific elements, which is kind of a pain. or i have to use !important, which i really like to avoid in my styles. so personally i'd rather have it left out or have an override for the default value. much better to be able to set it once and know that it will remain consistent. many sites don't use lucida, obviously, so i'm sure you can see why it can get tedious.

text shadow is along the same lines. it's easy enough to override it, but gets tedious when one has to do it repeatedly. i just think this kind of mixin would ideally avoid making assumptions about design decisions. it sounds like version 2 will go a long way in this direction, so i'll be looking forward to that for sure.

thanks for making it, regardless. it's quite handy, and gives me a good basis if i decide to roll my own or extend yours.
