### ISSUE TITLE
Disabled state

### ISSUE THREAD

**Issue by dlee** [imathis/fancy-buttons#3]
It would be nice to have disabled states on the buttons, although I'm not sure if disabled-ness can be detected via CSS.

**Comment by defkode** [comment]
can be detected, it's pseudo state like :hover
i.e: button:disabled

**Comment by imathis** [comment]
It's also possible to detect with the attribute selector button[disabled] which is a bit more accessible because no current version of IE supports :disabled. What a shame.

Anyway I've addressed this and released 0.3.7 which allows you to mark a button as disabled with the class="disabled" or by adding a disabled property to the button. Now the button will be more transparent and the state won't change for any interaction. Give it a shot and tell me if that's what you were looking for.

[Here's the diff](http://github.com/imathis/fancy-buttons/commit/fe026710b0b2f3b9e77a3d648ff905e98282da87)

**Comment by imathis** [comment]
I've updated the demo so you can see this in action: http://brandonmathis.com/projects/fancy-buttons/demo/

**Comment by dlee** [comment]
Cool, the demo works. Thanks!
