### ISSUE TITLE
Installation needs some love

### ISSUE THREAD

**Issue by activestylus** [imathis/fancy-buttons#8]
Right now there are just too many things that can go wrong. It's like the normal conventions dont apply.

@import  fancy-buttons.sass dont work, you have to do  @import fancy-buttons

None of this works properly unless you specify the exact version of fancy-buttons, compass, and compass-color, along with the sass cache in your config.

I realize this is very alpha (and also based on a rough version of compass) -  but you should definitely take a look at these threads and see what people are up against:

http://groups.google.com/group/compass-users/browse_thread/thread/ec74e2c2b5ea59e5
http://groups.google.com/group/compass-users/browse_thread/thread/b9a5a87b9c471fc5

**Comment by imathis** [comment]
These are issues related to the latest version of Compass, they have nothing to with my work on fancy buttons. Other plugins aren't having these issues because they don't depend on the latest version. Chris is very aware of the difficulties, and actually this has been a good thing in helping him work out bugs in Compass. Thanks for contacting me about this instead of just getting mad. I appreciate your willingness to help and I really wish it wasn't so hard for some people to use fancy buttons, but honestly these issues are things that will be fixed as Compass bugs get fixed. A lot has changed in Compass and it's going through some growing pains. When 0.10 is released, I'm hoping that all these bugs will be behind us.

**Comment by activestylus** [comment]
No probs - like I said its totally understandable, and this ticket is just the result of my own impatience because your plugin really does kick serious ass and I'd like to see more people using it.
